# Generated by Django 4.2.2 on 2023-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('cantidad_pedida', models.IntegerField()),
                ('plazo', models.CharField(choices=[('3', 3), ('6', 6), ('9', 9)], default='3', max_length=1)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
